version: '3.3'

services:
   appphp2020jhuan:
     depends_on:
       -  dbjhuan: 
     image: jhuansouza2/appphp2020jhuan:latest
     ports:
       - "8080:80"
     restart: always
     environment:
       - DB_HOST=dbjhuan
       - DB_USER=root
       - DB_PASSWORD=bob
       - DB_NAME=univille
   dbjhuan:
     image: mysql:5.7
     restart: always
#     ports:
#       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: bob
       MYSQL_DATABASE: univille
       MYSQL_USER: bob
       MYSQL_PASSWORD: bob
       volumes:

       - ./db/:/docker-entrypoint-initdb.d
